CREATE TABLE Users (
    id uuid GENERATED BY DEFAULT AS IDENTITY,
    username varchar NOT NULL,
    picture varchar NOT NULL
);

CREATE TABLE Decks (
    id uuid GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    description varchar NOT NULL,
    content jsonb NOT NULL,
    published bool default false,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);

